#!/bin/bash
getent group sededicated > /dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
    sudo groupadd -g 867 sededicated
    sudo usermod -a -G sededicated $USER
fi

mkdir -p appdata/space-engineers/bins/SpaceEngineersDedicated
mkdir -p appdata/space-engineers/bins/steamcmd
mkdir -p appdata/space-engineers/config/World
mkdir -p appdata/space-engineers/config/Plugins
if [ ! -f ./appdata/space-engineers/config/World/Sandbox.sbc ]; then
    echo "World not found, initalizing empty star system..."
    unzip -n star-system.zip -d ./appdata/space-engineers/config
fi

chown -R :sededicated ./appdata

sudo docker-compose up -d 
sudo docker-compose logs -f